#!/system/xbin/bash

#set LCD density
DENSITY=160
for x in $(cat /proc/cmdline); do
    case "$x" in
        android.lcd_density=*)
        echo "${x#android.lcd_density=}"
	DENSITY=${x#android.lcd_density=}
        ;;
    esac
done
setprop ro.sf.lcd_density $DENSITY

#copy a dist uEnv.txt from /system to /data
if [ ! -f /data/uEnv.txt ]; then
    echo "Creating /data/uEnv.txt"
    cp /system/uEnv.txt /data/uEnv.txt
    chmod 666 /data/uEnv.txt
fi

#prevent SSL certificates warnings
if [ `date +"%Y"` -eq "1970" ]; then
    date 010100002016 #MMDDhhmmYYYY
fi
